name: Build Theos Tweak

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install make perl python3

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos

      - name: Set environment
        run: echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build package
        run: |
          export THEOS=$HOME/theos
          make package

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: tweak-build
          path: packages/*.deb
